//DEFINE CONSTANT TO CALL ACTION, REDUCERS and SELECTOR
export const USER_LOGIN = "USER_LOGIN";

export const PRODUCT_ADD_TO_CART = "PRODUCT_ADD_TO_CART";
export const PRODUCT_LIST = "PRODUCT_LIST";
export const PRODUCT_REMOVE = "PRODUCT_REMOVE";

export const ACTION_LOGIN_REQUEST = "ACTION_LOGIN_REQUEST";

export const CART_LIST = "CART_LIST";
